/* eslint-disable max-len */
const cardsData = [
  {
    cardName: 'Bash',
    cardDescription: 'Bash é um acrônimo para "Bourne Again Shell" e foi desenvolvido em 1989 para suceder o Bourne Shell. É um programa shell executado em uma interface de linha de comando e tem como principal função controlar sistemas operacionais, sendo comumente utilizado no Linux e no macOS.',
    cardAttr1: '87',
    cardAttr2: '84',
    cardAttr3: '39',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Bootstrap',
    cardDescription: 'Bootstrap.css é um framework CSS que organiza e gerencia o layout de um site.',
    cardAttr1: '60',
    cardAttr2: '76',
    cardAttr3: '74',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Chrome',
    cardDescription: 'Navegador Web, muito versátil e popular.',
    cardAttr1: '79',
    cardAttr2: '49',
    cardAttr3: '82',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/chrome/chrome-original.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'CSS3',
    cardDescription: 'CSS3 é a terceira mais nova versão das famosas Cascading Style Sheets (ou simplesmente CSS), onde se define estilos para seu projeto web.',
    cardAttr1: '78',
    cardAttr2: '87',
    cardAttr3: '45',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-plain.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Docker',
    cardDescription: '\nO Docker é uma plataforma open source que facilita a criação e administração de ambientes isolados. Ele possibilita o empacotamento de uma aplicação ou ambiente dentro de um container, se tornando portátil para qualquer outro host que contenha o Docker instalado.',
    cardAttr1: '75',
    cardAttr2: '55',
    cardAttr3: '80',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-plain.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Eslint',
    cardDescription: 'O ESLint é uma ferramenta para você definir as regras e te mostrar eventualmente códigos que estão fora das regras de padronização já definidas pela sua equipe. ',
    cardAttr1: '77',
    cardAttr2: '43',
    cardAttr3: '90',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/eslint/eslint-original.svg',
    cardRare: 'muito raro',
    cardTrunfo: true,
  },
  {
    cardName: 'Express',
    cardDescription: 'O Express é um framework para aplicativo da web do Node.js mínimo e flexível que fornece um conjunto robusto de recursos para aplicativos web e móvel.',
    cardAttr1: '43',
    cardAttr2: '80',
    cardAttr3: '83',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Figma',
    cardDescription: 'O Figma é uma plataforma colaborativa para construção de design de interfaces e protótipos, pertencente a empresa Fima, Inc.',
    cardAttr1: '67',
    cardAttr2: '62',
    cardAttr3: '81',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Git',
    cardDescription: 'Git é o sistema de controle de versão open source mais usado no mundo atualmente! Ele é usado para controlar o histórico de alterações de arquivos e principalmente de projetos de desenvolvimento de software.',
    cardAttr1: '88',
    cardAttr2: '37',
    cardAttr3: '85',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'GitHub',
    cardDescription: 'GitHub é uma plataforma de hospedagem de código-fonte e arquivos com controle de versão usando o Git. ',
    cardAttr1: '85',
    cardAttr2: '75',
    cardAttr3: '50',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Google',
    cardDescription: 'Buscador que dispensa apresentações',
    cardAttr1: '57',
    cardAttr2: '79',
    cardAttr3: '74',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'HTML5',
    cardDescription: 'HTML5 é a quinta e última versão do HTML, sigla de Hypertext Markup Language, uma das primeiras e principais linguagens de marcação da web. O HTML serve, basicamente, para o desenvolvimento de páginas que contenham conteúdos simples, como textos, imagens, áudio, vídeos e etc.',
    cardAttr1: '83',
    cardAttr2: '74',
    cardAttr3: '53',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-plain.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Javascript',
    cardDescription: 'JavaScript (frequentemente abreviado como JS) é uma linguagem de programação interpretada estruturada, de script em alto nível com tipagem dinâmica fraca e multiparadigma (protótipos, orientado a objeto, imperativo e funcional)',
    cardAttr1: '35',
    cardAttr2: '88',
    cardAttr3: '87',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Jest',
    cardDescription: 'Jest é um poderoso framework de testes em JavaScript com foco na simplicidade.',
    cardAttr1: '78',
    cardAttr2: '53',
    cardAttr3: '79',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Linkedin',
    cardDescription: 'Com mais de 300 milhões de membros, o LinkedIn é a maior rede social profissional que existe.',
    cardAttr1: '46',
    cardAttr2: '87',
    cardAttr3: '77',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg',
    cardRare: 'muito raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Linux',
    cardDescription: 'O Linux é um sistema operacional open source e gratuito, disponibilizado sob a Licença Pública Geral (GPL) GNU. ',
    cardAttr1: '67',
    cardAttr2: '77',
    cardAttr3: '66',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Mocha',
    cardDescription: 'Mocha é uma estrutura de teste JavaScript para programas Node.js, com suporte a navegadores, testes assíncronos, relatórios de cobertura de testes e uso de qualquer biblioteca de asserção. ',
    cardAttr1: '84',
    cardAttr2: '83',
    cardAttr3: '43',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mocha/mocha-plain.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'MongoDB',
    cardDescription: 'MongoDB é um software de banco de dados orientado a documentos livre, de código aberto e multiplataforma, escrito na linguagem C++. Classificado como um programa de banco de dados NoSQL, o MongoDB usa documentos semelhantes a JSON com esquemas.',
    cardAttr1: '77',
    cardAttr2: '84',
    cardAttr3: '49',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'MySQL',
    cardDescription: 'O MySQL é um sistema de gerenciamento de banco de dados, que utiliza a linguagem SQL como interface.',
    cardAttr1: '69',
    cardAttr2: '85',
    cardAttr3: '56',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Node.js',
    cardDescription: 'Node.js é um software de código aberto, multiplataforma, baseado no interpretador V8 do Google e que permite a execução de códigos JavaScript fora de um navegador web. A principal característica do Node.js é sua arquitetura assíncrona e orientada por eventos.',
    cardAttr1: '75',
    cardAttr2: '55',
    cardAttr3: '80',
    cardImage: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
    cardRare: 'raro',
    cardTrunfo: false,
  },
];

export default cardsData;
